# Site settings
title: kill the (sub)routine 
email: eddy@killthesubroutine.com
description: > # this means to ignore newlines until "baseurl:"
    thoughts on app development and life refactoring
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.killthesubroutine.com" # the base hostname & protocol for your site
twitter_username: ejosafat 
github_username: ejosafat

# Build settings
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    syntax_highlighter: rouge
    syntax_highlighter_options:
        default_lang: javascript
gems:
    - jekyll-feed
    - jekyll-mentions
